WPWD=$(shell pwd)
VERILOG_SOURCES = $(WPWD)/../../rtl/verilog/spi_slave.v

TOPLEVEL := SPI_slave
MODULE   := test_spi_slave

include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim
